# Generated by Django 4.2.10 on 2026-04-25 10:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActividadPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_actividad', models.CharField(choices=[('C', 'Conferencia'), ('CE', 'Conferencia Especial'), ('CP', 'Clase Práctica'), ('L', 'Laboratorio'), ('S', 'Seminario'), ('T', 'Taller'), ('TE', 'Taller de Ejercicios'), ('E', 'Educación Física'), ('PP', 'Práctica Profesional'), ('NP', 'No Presencial')], max_length=3, verbose_name='Tipo de actividad')),
                ('semana', models.PositiveSmallIntegerField(help_text='Número de semana según el archivo importado', verbose_name='Semana del balance')),
                ('dia_semana', models.PositiveSmallIntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes')], help_text='0=Lunes, 1=Martes, 2=Miércoles, 3=Jueves', verbose_name='Día de la semana (balance)')),
                ('requiere_local', models.BooleanField(default=True, help_text='False para actividades NP (no presenciales)', verbose_name='Requiere local')),
            ],
            options={
                'verbose_name': 'Actividad Planificada',
                'verbose_name_plural': 'Actividades Planificadas',
                'ordering': ['anio__numero', 'semana', 'dia_semana', 'tipo_actividad'],
            },
        ),
        migrations.CreateModel(
            name='AnioAcademico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveSmallIntegerField(help_text='Valores permitidos: 1, 2, 3, 4', unique=True, verbose_name='Número de año')),
                ('turno', models.CharField(choices=[('M', 'Mañana'), ('T', 'Tarde')], max_length=1, verbose_name='Turno')),
            ],
            options={
                'verbose_name': 'Año Académico',
                'verbose_name_plural': 'Años Académicos',
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre completo')),
                ('usuario', models.OneToOneField(blank=True, help_text='Si el profesor también es usuario del sistema (rol CONSULTA)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profesor', to=settings.AUTH_USER_MODEL, verbose_name='Usuario del sistema')),
            ],
            options={
                'verbose_name': 'Profesor',
                'verbose_name_plural': 'Profesores',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Ej. S401, A201, LAB1, POLI', max_length=20, unique=True, verbose_name='Código único')),
                ('nombre', models.CharField(blank=True, help_text='Ej. Salón 401, Aula 201', max_length=100, verbose_name='Nombre descriptivo')),
                ('tipo', models.CharField(choices=[('AULA', 'Aula'), ('SALON', 'Salón de Conferencia'), ('LAB', 'Laboratorio'), ('POLI', 'Polideportivo'), ('OTRO', 'Otro')], max_length=5, verbose_name='Tipo de local')),
                ('capacidad', models.PositiveIntegerField(verbose_name='Capacidad (número de alumnos)')),
            ],
            options={
                'verbose_name': 'Local',
                'verbose_name_plural': 'Locales',
                'ordering': ['tipo', 'codigo'],
                'indexes': [models.Index(fields=['tipo', 'capacidad'], name='idx_local_tipo_cap')],
            },
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej. G1, G2, Grupo A…', max_length=50, verbose_name='Nombre del grupo')),
                ('cantidad_alumnos', models.PositiveIntegerField(help_text='Se usa para validar la capacidad del local asignado', verbose_name='Cantidad de alumnos')),
                ('anio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos', to='academico.anioacademico', verbose_name='Año académico')),
            ],
            options={
                'verbose_name': 'Grupo',
                'verbose_name_plural': 'Grupos',
                'ordering': ['anio__numero', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='FranjaHoraria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turno', models.CharField(choices=[('M', 'Mañana'), ('T', 'Tarde')], max_length=1, verbose_name='Turno')),
                ('orden', models.PositiveSmallIntegerField(help_text='Número secuencial dentro del turno: 1, 2, 3, 4…', verbose_name='Orden de presentación')),
                ('hora_inicio', models.TimeField(verbose_name='Hora de inicio')),
                ('hora_fin', models.TimeField(verbose_name='Hora de fin')),
            ],
            options={
                'verbose_name': 'Franja Horaria',
                'verbose_name_plural': 'Franjas Horarias',
                'ordering': ['turno', 'orden'],
                'indexes': [models.Index(fields=['turno', 'orden'], name='idx_franja_turno_ord')],
                'unique_together': {('turno', 'orden')},
            },
        ),
        migrations.CreateModel(
            name='Auditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('IMPORTAR_BALANCE', 'Importar Balance de Carga'), ('GENERAR_HORARIO', 'Generar Horario Automático'), ('MODIFICAR_ASIGNACION', 'Modificar Asignación Manual'), ('CREAR_USUARIO', 'Crear Usuario'), ('EDITAR_USUARIO', 'Editar Usuario'), ('ELIMINAR_USUARIO', 'Eliminar Usuario'), ('INICIO_SESION', 'Inicio de Sesión'), ('CIERRE_SESION', 'Cierre de Sesión'), ('ERROR_SOLVER', 'Error del Motor de Optimización')], max_length=50, verbose_name='Acción')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y hora')),
                ('detalles', models.TextField(blank=True, help_text='Información adicional en formato JSON o texto descriptivo', verbose_name='Detalles')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('navegador', models.CharField(blank=True, max_length=255, null=True, verbose_name='Navegador/Agente de Usuario')),
                ('usuario', models.ForeignKey(blank=True, help_text='NULL si la acción es automática (ej. error del solver)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditorias', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Registro de Auditoría',
                'verbose_name_plural': 'Registros de Auditoría',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre completo')),
                ('abreviatura', models.CharField(help_text='Máximo 10 caracteres. Se muestra en la tabla horaria.', max_length=10, verbose_name='Abreviatura')),
                ('anio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaturas', to='academico.anioacademico', verbose_name='Año académico')),
            ],
            options={
                'verbose_name': 'Asignatura',
                'verbose_name_plural': 'Asignaturas',
                'ordering': ['anio__numero', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='AsignacionProfesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_actividad', models.CharField(choices=[('C', 'Conferencia'), ('CE', 'Conferencia Especial'), ('CP', 'Clase Práctica'), ('L', 'Laboratorio'), ('S', 'Seminario'), ('T', 'Taller'), ('TE', 'Taller de Ejercicios'), ('E', 'Educación Física'), ('PP', 'Práctica Profesional'), ('NP', 'No Presencial')], help_text='Indica la modalidad que imparte este profesor', max_length=3, verbose_name='Tipo de actividad')),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_profesor', to='academico.asignatura', verbose_name='Asignatura')),
                ('grupo', models.ForeignKey(blank=True, help_text='Dejar en blanco para conferencia (todo el año)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_profesor', to='academico.grupo', verbose_name='Grupo')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='academico.profesor', verbose_name='Profesor')),
            ],
            options={
                'verbose_name': 'Asignación Profesor',
                'verbose_name_plural': 'Asignaciones de Profesores',
                'ordering': ['profesor__nombre', 'asignatura__nombre'],
            },
        ),
        migrations.CreateModel(
            name='Asignacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.PositiveSmallIntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes')], help_text='0=Lunes … 4=Viernes. Puede diferir del día del balance porque el solver puede reubicar la actividad.', verbose_name='Día de la semana final')),
                ('manual', models.BooleanField(default=False, help_text='True si el planificador modificó esta asignación tras la generación automática', verbose_name='Editada manualmente')),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de generación')),
                ('actividad_plan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='asignacion', to='academico.actividadplan', verbose_name='Actividad planificada')),
                ('franja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='academico.franjahoraria', verbose_name='Franja horaria')),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='academico.local', verbose_name='Local asignado')),
                ('profesor', models.ForeignKey(blank=True, help_text='Se deriva de AsignacionProfesor; puede quedar NULL si no se definió previamente la asignación profesor-materia.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asignaciones_horario', to='academico.profesor', verbose_name='Profesor asignado')),
            ],
            options={
                'verbose_name': 'Asignación',
                'verbose_name_plural': 'Asignaciones',
                'ordering': ['dia_semana', 'franja__orden'],
            },
        ),
        migrations.AddConstraint(
            model_name='anioacademico',
            constraint=models.CheckConstraint(check=models.Q(('numero__gte', 1), ('numero__lte', 4)), name='anio_numero_1_a_4'),
        ),
        migrations.AddField(
            model_name='actividadplan',
            name='anio',
            field=models.ForeignKey(help_text='Denormalizado para agilizar filtros (ya se infiere por asignatura)', on_delete=django.db.models.deletion.CASCADE, related_name='actividades_plan', to='academico.anioacademico', verbose_name='Año académico'),
        ),
        migrations.AddField(
            model_name='actividadplan',
            name='asignatura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades_plan', to='academico.asignatura', verbose_name='Asignatura'),
        ),
        migrations.AddField(
            model_name='actividadplan',
            name='grupo',
            field=models.ForeignKey(blank=True, help_text='NULL para conferencias (afecta a todos los grupos del año)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actividades_plan', to='academico.grupo', verbose_name='Grupo'),
        ),
        migrations.AddIndex(
            model_name='grupo',
            index=models.Index(fields=['anio', 'nombre'], name='idx_grupo_anio_nombre'),
        ),
        migrations.AlterUniqueTogether(
            name='grupo',
            unique_together={('anio', 'nombre')},
        ),
        migrations.AddIndex(
            model_name='auditoria',
            index=models.Index(fields=['-fecha'], name='idx_aud_fecha'),
        ),
        migrations.AddIndex(
            model_name='auditoria',
            index=models.Index(fields=['usuario', '-fecha'], name='idx_aud_usuario_fecha'),
        ),
        migrations.AddIndex(
            model_name='auditoria',
            index=models.Index(fields=['accion', '-fecha'], name='idx_aud_accion_fecha'),
        ),
        migrations.AddIndex(
            model_name='asignatura',
            index=models.Index(fields=['anio', 'abreviatura'], name='idx_asig_anio_abrev'),
        ),
        migrations.AlterUniqueTogether(
            name='asignatura',
            unique_together={('anio', 'abreviatura')},
        ),
        migrations.AddIndex(
            model_name='asignacionprofesor',
            index=models.Index(fields=['asignatura', 'tipo_actividad', 'grupo'], name='idx_asignprof_asig_tipo_grp'),
        ),
        migrations.AlterUniqueTogether(
            name='asignacionprofesor',
            unique_together={('profesor', 'asignatura', 'grupo', 'tipo_actividad')},
        ),
        migrations.AddIndex(
            model_name='asignacion',
            index=models.Index(fields=['dia_semana', 'franja', 'local'], name='idx_asig_dia_franja_local'),
        ),
        migrations.AddIndex(
            model_name='asignacion',
            index=models.Index(fields=['dia_semana', 'franja'], name='idx_asig_dia_franja'),
        ),
        migrations.AddIndex(
            model_name='asignacion',
            index=models.Index(fields=['actividad_plan'], name='idx_asig_actplan'),
        ),
        migrations.AlterUniqueTogether(
            name='asignacion',
            unique_together={('franja', 'local', 'dia_semana')},
        ),
        migrations.AddIndex(
            model_name='actividadplan',
            index=models.Index(fields=['anio', 'semana'], name='idx_actplan_anio_sem'),
        ),
        migrations.AddIndex(
            model_name='actividadplan',
            index=models.Index(fields=['asignatura', 'tipo_actividad', 'grupo'], name='idx_actplan_asig_tipo_grp'),
        ),
    ]
