# Generated by Django 4.2.10 on 2026-04-25 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsignacionAulaGrupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo', models.OneToOneField(help_text='Grupo al que se le asigna el aula base.', on_delete=django.db.models.deletion.CASCADE, related_name='aula_fija', to='academico.grupo', verbose_name='Grupo')),
                ('local', models.ForeignKey(help_text='Aula base donde el grupo recibe sus clases regulares.', on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_grupo', to='academico.local', verbose_name='Aula')),
            ],
            options={
                'verbose_name': 'Asignación de Aula a Grupo',
                'verbose_name_plural': 'Asignaciones de Aulas a Grupos',
                'ordering': ['grupo__anio__numero', 'grupo__nombre'],
            },
        ),
    ]
