# Generated by Django 4.2.10 on 2026-04-26 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0002_asignacionaulagrupo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignacion',
            name='franja',
            field=models.ForeignKey(blank=True, help_text='NULL si la asignación es virtual o está pendiente de franja real', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='academico.franjahoraria', verbose_name='Franja horaria'),
        ),
        migrations.AlterField(
            model_name='asignacion',
            name='local',
            field=models.ForeignKey(blank=True, help_text='NULL si la asignación es virtual o está pendiente de local real', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='academico.local', verbose_name='Local asignado'),
        ),
    ]
